import type { InstExam, InstLesson } from "./instrument-curriculum";

export const BAT_ORDER = ["bat-kit", "bat-tempo", "bat-grooves", "bat-fills"];

export const BAT_LESSONS: InstLesson[] = [
  {
    id: "bat-kit",
    titleFr: "Le kit : qui fait quoi",
    titleEn: "The kit: who does what",
    introFr: [
      "Grosse caisse au pied : les temps, le socle. Caisse claire : les contretemps 2 et 4, le claquement qui fait hocher la tête. Charleston : le débit, la subdivision qui fait rouler.",
      "Toms : les descentes de breaks. Cymbales : la ponctuation — crash pour marquer, ride pour rouler long. Chaque pièce a un rôle, comme chaque musicien.",
    ],
    introEn: [
      "Kick on foot: the beats, the bedrock. Snare: backbeats 2 and 4, the crack that nods heads. Hi-hat: the flow, the subdivision that rolls.",
      "Toms: fill runs. Cymbals: punctuation — crash to mark, ride to cruise. Every piece has a role, like every musician.",
    ],
    questions: [
      {
        qFr: "Qui claque sur les temps 2 et 4 ?",
        qEn: "What cracks on beats 2 and 4?",
        optionsFr: ["La caisse claire", "La grosse caisse", "Le charleston", "Le tom grave"],
        optionsEn: ["The snare", "The kick", "The hi-hat", "The low tom"],
        answer: 0,
        explainFr: "La claire sur 2 et 4 : le claquement du rock.",
        explainEn: "Snare on 2 and 4: the rock crack.",
      },
      {
        qFr: "Le charleston apporte surtout…",
        qEn: "The hi-hat mostly brings…",
        optionsFr: ["les temps forts", "la subdivision, le débit", "les accents de fin", "la mélodie"],
        optionsEn: ["the downbeats", "the subdivision, the flow", "the ending accents", "the melody"],
        answer: 1,
        explainFr: "Croches ou doubles-croches : c'est lui qui fait rouler.",
        explainEn: "Eighths or sixteenths: it's what makes it roll.",
      },
      {
        qFr: "Le crash sert à…",
        qEn: "The crash is for…",
        optionsFr: ["marquer une section, accentuer", "garder le tempo seul", "jouer la mélodie", "remplacer la claire"],
        optionsEn: ["marking a section, accenting", "keeping time alone", "playing the melody", "replacing the snare"],
        answer: 0,
        explainFr: "Un coup de crash = ponctuation, début de refrain, final.",
        explainEn: "A crash hit = punctuation, chorus start, finale.",
      },
      {
        qFr: "La grosse caisse se joue…",
        qEn: "The kick is played…",
        optionsFr: ["à la main gauche", "au pied, à la pédale", "aux balais", "au genou"],
        optionsEn: ["with the left hand", "with the foot, on the pedal", "with brushes", "with the knee"],
        answer: 1,
        explainFr: "Pédale au pied droit : les temps, le socle.",
        explainEn: "Right-foot pedal: the beats, the bedrock.",
      },
    ],
  },
  {
    id: "bat-tempo",
    titleFr: "Pulsation et tempo",
    titleEn: "Pulse and tempo",
    introFr: [
      "Le tempo se mesure en BPM — battements par minute. 100 BPM = 100 temps par minute. En 4/4, une mesure compte 4 temps, et le temps 1 (downbeat) est le plus marqué.",
      "Entre les temps vivent les contretemps (le « et ») : c'est là que naissent le groove et les syncopes. Compte « 1 et 2 et 3 et 4 et » et tu tiens la grille.",
    ],
    introEn: [
      "Tempo is measured in BPM — beats per minute. 100 BPM = 100 beats per minute. In 4/4, a bar holds 4 beats, and beat 1 (the downbeat) hits hardest.",
      "Between beats live the offbeats (the 'and'): that's where groove and syncopation are born. Count '1 and 2 and 3 and 4 and' and you own the grid.",
    ],
    questions: [
      {
        qFr: "100 BPM signifie…",
        qEn: "100 BPM means…",
        optionsFr: ["100 temps par minute", "100 mesures par minute", "100 croches par seconde", "100 décibels"],
        optionsEn: ["100 beats per minute", "100 bars per minute", "100 eighths per second", "100 decibels"],
        answer: 0,
        explainFr: "Beats Per Minute : le métronome du morceau.",
        explainEn: "Beats Per Minute: the song's metronome.",
      },
      {
        qFr: "Une mesure à 4/4 contient…",
        qEn: "A 4/4 bar holds…",
        optionsFr: ["3 temps", "4 temps", "4 mesures", "8 temps"],
        optionsEn: ["3 beats", "4 beats", "4 bars", "8 beats"],
        answer: 1,
        explainFr: "4 noires par mesure : compte 1-2-3-4.",
        explainEn: "4 quarters per bar: count 1-2-3-4.",
      },
      {
        qFr: "Le contretemps, c'est…",
        qEn: "The offbeat is…",
        optionsFr: ["entre les temps (le « et »)", "le temps 1", "la fin du morceau", "un silence total"],
        optionsEn: ["between beats (the 'and')", "beat 1", "the song's end", "total silence"],
        answer: 0,
        explainFr: "« 1 ET 2 ET » : le ET porte le groove.",
        explainEn: "'1 AND 2 AND': the AND carries the groove.",
      },
      {
        qFr: "Le temps 1 d'une mesure est…",
        qEn: "Beat 1 of a bar is…",
        optionsFr: ["le plus faible", "le plus marqué", "optionnel", "toujours vide"],
        optionsEn: ["the weakest", "the strongest", "optional", "always empty"],
        answer: 1,
        explainFr: "Downbeat : tout le groupe s'y repère.",
        explainEn: "Downbeat: the whole band finds itself there.",
      },
    ],
  },
  {
    id: "bat-grooves",
    titleFr: "Rock, punk, funk, bossa",
    titleEn: "Rock, punk, funk, bossa",
    introFr: [
      "Rock : grosse caisse aux temps 1 et 3, claire aux 2 et 4. Punk : la même base, mais la grosse caisse martèle TOUS les temps. Deux cases de différence sur la grille, deux énergies opposées.",
      "Funk : charleston en doubles-croches et grosse caisse syncopée. Bossa-nova : grosse caisse décalée et charleston ouvert qui respire. Écoute où tombe la grosse caisse : elle dit le style.",
    ],
    introEn: [
      "Rock: kick on beats 1 and 3, snare on 2 and 4. Punk: same skeleton, but the kick hammers EVERY beat. Two grid cells apart, opposite energies.",
      "Funk: sixteenth-note hi-hat and syncopated kick. Bossa-nova: off-beat kick and breathing open hi-hat. Listen where the kick lands: it names the style.",
    ],
    questions: [
      {
        qFr: "En rock, la grosse caisse joue…",
        qEn: "In rock, the kick plays…",
        optionsFr: ["les temps 1 et 3", "tous les temps", "les contretemps", "au hasard"],
        optionsEn: ["beats 1 and 3", "every beat", "the offbeats", "randomly"],
        answer: 0,
        explainFr: "1 et 3 à la grosse, 2 et 4 à la claire.",
        explainEn: "1 and 3 on kick, 2 and 4 on snare.",
      },
      {
        qFr: "Le punk se reconnaît à…",
        qEn: "Punk stands out by…",
        optionsFr: ["l'absence de claire", "la grosse caisse sur tous les temps", "un tempo lent", "des balais"],
        optionsEn: ["no snare", "kick on every beat", "a slow tempo", "brushes"],
        answer: 1,
        explainFr: "4 coups de grosse par mesure : ça pousse.",
        explainEn: "4 kick hits per bar: it pushes.",
      },
      {
        qFr: "La signature du funk au charleston ?",
        qEn: "Funk's hi-hat signature?",
        optionsFr: ["les doubles-croches", "la ronde", "le silence", "le roulement"],
        optionsEn: ["sixteenth notes", "the whole note", "silence", "the roll"],
        answer: 0,
        explainFr: "16 coups par mesure : le sifflement du funk.",
        explainEn: "16 hits per bar: the funk hiss.",
      },
      {
        qFr: "La bossa-nova se repère à…",
        qEn: "Bossa-nova shows in…",
        optionsFr: ["la double pédale", "la grosse caisse décalée", "un blast beat", "l'absence de cymbales"],
        optionsEn: ["the double pedal", "the off-beat kick", "a blast beat", "no cymbals"],
        answer: 1,
        explainFr: "La grosse tombe à côté des temps : ça balance.",
        explainEn: "The kick lands beside the beats: it sways.",
      },
    ],
  },
  {
    id: "bat-fills",
    titleFr: "Breaks et ponctuation",
    titleEn: "Fills and punctuation",
    introFr: [
      "Un break (fill) marque la fin d'une phrase : une mesure où tu quittes le rythme pour une descente — souvent caisse claire puis toms du aigu au grave — avant de retomber sur le temps 1.",
      "Il se termine presque toujours par un crash sur le 1 de la section suivante. Règle d'or : un break sert la musique, jamais l'ego — reviens toujours en place.",
    ],
    introEn: [
      "A fill marks a phrase ending: one bar off-pattern for a run — often snare then toms high to low — landing back on beat 1.",
      "It almost always ends with a crash on the next section's 1. Golden rule: a fill serves the music, never the ego — always land back in time.",
    ],
    questions: [
      {
        qFr: "Un break sert à…",
        qEn: "A fill is for…",
        optionsFr: ["marquer une transition", "remplir tous les silences", "jouer plus fort tout le temps", "improviser 5 minutes"],
        optionsEn: ["marking a transition", "filling every silence", "playing louder nonstop", "improvising 5 minutes"],
        answer: 0,
        explainFr: "Fin de couplet, arrivée du refrain : le break annonce.",
        explainEn: "Verse end, chorus coming: the fill announces.",
      },
      {
        qFr: "Un break se termine souvent par…",
        qEn: "A fill often ends with…",
        optionsFr: ["un roulement infini", "un crash sur le temps 1", "un solo de pied", "un arrêt net sans suite"],
        optionsEn: ["an endless roll", "a crash on beat 1", "a foot solo", "a dead stop"],
        answer: 1,
        explainFr: "Crash sur le 1 : la nouvelle section démarre.",
        explainEn: "Crash on the 1: the new section starts.",
      },
      {
        qFr: "La descente de toms va…",
        qEn: "The tom run goes…",
        optionsFr: ["de l'aigu vers le grave", "du grave vers l'aigu", "sur un seul tom", "sans les baguettes"],
        optionsEn: ["high to low", "low to high", "on one tom", "without sticks"],
        answer: 0,
        explainFr: "Tom aigu → tom grave : la chute naturelle.",
        explainEn: "High tom → low tom: the natural fall.",
      },
      {
        qFr: "Après un break, l'essentiel c'est…",
        qEn: "After a fill, what matters is…",
        optionsFr: ["enchaîner un deuxième break", "retomber en place sur le rythme", "accélérer le tempo", "s'arrêter"],
        optionsEn: ["chaining a second fill", "landing back in time", "speeding up", "stopping"],
        answer: 1,
        explainFr: "Le break n'existe que pour mieux revenir au groove.",
        explainEn: "The fill only exists to return to the groove.",
      },
    ],
  },
];

export const BAT_EXAM: InstExam = {
  id: "bat-examen",
  titleFr: "Examen du batteur",
  titleEn: "Drummer exam",
  leadFr: "6 questions sur tout le parcours batterie. 60 % pour valider, +50 XP et badge Expert.",
  leadEn: "6 questions across the whole drum path. 60% to pass, +50 XP and the Expert badge.",
  questions: [
    {
      qFr: "Sur quels temps claque la caisse claire en rock ?",
      qEn: "Which beats does the snare crack in rock?",
      optionsFr: ["2 et 4", "1 et 3", "1, 2, 3, 4", "Jamais"],
      optionsEn: ["2 and 4", "1 and 3", "1, 2, 3, 4", "Never"],
      answer: 0,
      explainFr: "Backbeat : 2 et 4, toujours.",
      explainEn: "Backbeat: 2 and 4, always.",
    },
    {
      qFr: "120 BPM, c'est…",
      qEn: "120 BPM is…",
      optionsFr: ["120 mesures", "120 temps par minute", "2 heures", "très lent"],
      optionsEn: ["120 bars", "120 beats per minute", "2 hours", "very slow"],
      answer: 1,
      explainFr: "2 temps par seconde : un rock qui avance.",
      explainEn: "2 beats per second: driving rock.",
    },
    {
      qFr: "Punk contre rock : que fait la grosse caisse ?",
      qEn: "Punk vs rock: what does the kick do?",
      optionsFr: ["Elle joue tous les temps", "Elle se tait", "Elle joue les contretemps", "Elle ralentit"],
      optionsEn: ["It plays every beat", "It stays silent", "It plays offbeats", "It slows down"],
      answer: 0,
      explainFr: "4 temps martelés : la marque du punk.",
      explainEn: "4 hammered beats: the punk mark.",
    },
    {
      qFr: "Le funk au charleston : quelle subdivision ?",
      qEn: "Funk on hi-hat: which subdivision?",
      optionsFr: ["Rondes", "Triolets lents", "Doubles-croches", "Silences"],
      optionsEn: ["Whole notes", "Slow triplets", "Sixteenths", "Rests"],
      answer: 2,
      explainFr: "16 coups par mesure : le débit du funk.",
      explainEn: "16 hits per bar: the funk flow.",
    },
    {
      qFr: "Un break de fin de couplet se termine par…",
      qEn: "A verse-ending fill closes with…",
      optionsFr: ["un crash sur le 1", "un roulement infini", "un stop brutal définitif", "un changement de tempo"],
      optionsEn: ["a crash on the 1", "an endless roll", "a final dead stop", "a tempo change"],
      answer: 0,
      explainFr: "Crash + temps 1 : le refrain peut partir.",
      explainEn: "Crash + beat 1: the chorus can launch.",
    },
    {
      qFr: "La bossa-nova : où tombe la grosse caisse ?",
      qEn: "Bossa-nova: where does the kick land?",
      optionsFr: ["Sur tous les temps", "Jamais", "À côté des temps (décalée)", "Avec la claire"],
      optionsEn: ["On every beat", "Never", "Beside the beats (off-beat)", "With the snare"],
      answer: 2,
      explainFr: "Syncopée : c'est ce décalage qui balance.",
      explainEn: "Syncopated: that offset is the sway.",
    },
  ],
};
