import type { InstExam, InstLesson } from "./instrument-curriculum";

export const BASSE_ORDER = ["basse-role", "basse-notes", "basse-gammes", "basse-groove"];

export const BASSE_LESSONS: InstLesson[] = [
  {
    id: "basse-role",
    titleFr: "Ton rôle : la fondation",
    titleEn: "Your job: the foundation",
    introFr: [
      "La basse fait le lien entre le rythme et l'harmonie : tu joues les fondamentales des accords, verrouillé avec la grosse caisse. Quand basse et batterie respirent ensemble, tout le groupe sonne.",
      "Ta basse a 4 cordes — Mi, La, Ré, Sol, du grave à l'aigu — et sonne une octave sous la guitare. Moins de notes, plus de poids : chaque note compte.",
    ],
    introEn: [
      "Bass bridges rhythm and harmony: you play chord roots, locked in with the kick drum. When bass and drums breathe together, the whole band sounds right.",
      "Your bass has 4 strings — E, A, D, G, low to high — sounding one octave below guitar. Fewer notes, more weight: every note counts.",
    ],
    questions: [
      {
        qFr: "Combien de cordes a une basse standard ?",
        qEn: "How many strings does a standard bass have?",
        optionsFr: ["4", "5", "6", "7"],
        optionsEn: ["4", "5", "6", "7"],
        answer: 0,
        explainFr: "Mi – La – Ré – Sol : 4 cordes suffisent à porter tout un groupe.",
        explainEn: "E – A – D – G: 4 strings carry a whole band.",
      },
      {
        qFr: "La basse sonne…",
        qEn: "The bass sounds…",
        optionsFr: ["comme la guitare", "une octave sous la guitare", "une octave au-dessus", "deux octaves sous"],
        optionsEn: ["like the guitar", "one octave below guitar", "one octave above", "two octaves below"],
        answer: 1,
        explainFr: "Mêmes notes que la guitare, un étage plus bas : c'est la fondation.",
        explainEn: "Same notes as guitar, one floor down: that's the foundation.",
      },
      {
        qFr: "Avec quel élément le bassiste verrouille-t-il le groove ?",
        qEn: "What does the bassist lock the groove with?",
        optionsFr: ["La grosse caisse", "La voix", "Le solo de guitare", "Les cymbales"],
        optionsEn: ["The kick drum", "The vocals", "The guitar solo", "The cymbals"],
        answer: 0,
        explainFr: "Fondamentale sur les coups de grosse caisse : le socle du morceau.",
        explainEn: "Root on the kick hits: the bedrock of the song.",
      },
      {
        qFr: "Quelles notes portes-tu en priorité ?",
        qEn: "Which notes do you carry first?",
        optionsFr: ["Les extensions jazz", "Les fondamentales des accords", "Les harmoniques", "Les bends"],
        optionsEn: ["Jazz extensions", "Chord roots", "Harmonics", "Bends"],
        answer: 1,
        explainFr: "D'abord la fondamentale, juste et en place. Le reste vient après.",
        explainEn: "Root first, in tune and in time. The rest comes later.",
      },
    ],
  },
  {
    id: "basse-notes",
    titleFr: "Les notes sur 4 cordes",
    titleEn: "Notes on 4 strings",
    introFr: [
      "Cordes à vide : Mi (4e), La (3e), Ré (2e), Sol (1re). Chaque case monte d'un demi-ton, et la case 12 rejoue la corde à vide une octave plus haut — un repère en or.",
      "Le raccourci des bassistes : l'octave se trouve 2 cordes plus aigu et 2 cases plus loin. De La case 5, l'octave est corde de Sol case 7.",
    ],
    introEn: [
      "Open strings: E (4th), A (3rd), D (2nd), G (1st). Each fret goes up a semitone, and fret 12 replays the open string one octave up — a golden landmark.",
      "The bassist's shortcut: the octave sits 2 strings up and 2 frets over. From A fret 5, the octave is G-string fret 7.",
    ],
    questions: [
      {
        qFr: "Que joue la case 12 d'une corde ?",
        qEn: "What does fret 12 play?",
        optionsFr: ["La même note, une octave plus haut", "La quinte", "Une autre note", "Rien de précis"],
        optionsEn: ["The same note, one octave up", "The fifth", "Another note", "Nothing precise"],
        answer: 0,
        explainFr: "12 demi-tons = une octave : même nom, plus haut.",
        explainEn: "12 semitones = one octave: same name, higher.",
      },
      {
        qFr: "Corde de La, case 2 : quelle note ?",
        qEn: "A string, fret 2: which note?",
        optionsFr: ["Do (C)", "Si (B)", "Sol (G)", "La# (A#)"],
        optionsEn: ["C", "B", "G", "A#"],
        answer: 1,
        explainFr: "La + 2 demi-tons = Si.",
        explainEn: "A + 2 semitones = B.",
      },
      {
        qFr: "La forme d'octave, c'est…",
        qEn: "The octave shape is…",
        optionsFr: ["2 cordes + 2 cases", "1 corde + 12 cases", "3 cordes + 1 case", "2 cases sur la même corde"],
        optionsEn: ["2 strings + 2 frets", "1 string + 12 frets", "3 strings + 1 fret", "2 frets on one string"],
        answer: 0,
        explainFr: "Deux cordes vers l'aigu, deux cases plus loin : l'octave.",
        explainEn: "Two strings up, two frets over: the octave.",
      },
      {
        qFr: "Corde de Mi, case 3 : quelle note ?",
        qEn: "E string, fret 3: which note?",
        optionsFr: ["Fa (F)", "Sol (G)", "La (A)", "Sol# (G#)"],
        optionsEn: ["F", "G", "A", "G#"],
        answer: 1,
        explainFr: "Mi + 3 demi-tons = Sol.",
        explainEn: "E + 3 semitones = G.",
      },
    ],
  },
  {
    id: "basse-gammes",
    titleFr: "Gammes : majeure et mineure",
    titleEn: "Scales: major and minor",
    introFr: [
      "La gamme majeure se construit en demi-tons : 0 – 2 – 4 – 5 – 7 – 9 – 11. Retiens surtout son squelette : fondamentale (0), tierce majeure (+4), quinte (+7) — la triade qui porte 90 % de tes lignes.",
      "La mineure naturelle abaisse la tierce (+3 au lieu de +4) : 0 – 2 – 3 – 5 – 7 – 8 – 10. Une seule case de différence, une couleur opposée.",
    ],
    introEn: [
      "The major scale builds in semitones: 0 – 2 – 4 – 5 – 7 – 9 – 11. Remember its skeleton above all: root (0), major third (+4), fifth (+7) — the triad behind 90% of your lines.",
      "Natural minor lowers the third (+3 instead of +4): 0 – 2 – 3 – 5 – 7 – 8 – 10. One fret apart, opposite color.",
    ],
    questions: [
      {
        qFr: "La tierce majeure vaut…",
        qEn: "The major third is…",
        optionsFr: ["4 demi-tons", "3 demi-tons", "5 demi-tons", "7 demi-tons"],
        optionsEn: ["4 semitones", "3 semitones", "5 semitones", "7 semitones"],
        answer: 0,
        explainFr: "Do → Mi : 4 cases. C'est elle qui rend un accord majeur.",
        explainEn: "C → E: 4 frets. It's what makes a chord major.",
      },
      {
        qFr: "Les degrés d'une triade ?",
        qEn: "The degrees of a triad?",
        optionsFr: ["1 – 2 – 5", "1 – 3 – 5", "1 – 4 – 5", "2 – 4 – 6"],
        optionsEn: ["1 – 2 – 5", "1 – 3 – 5", "1 – 4 – 5", "2 – 4 – 6"],
        answer: 1,
        explainFr: "Fondamentale, tierce, quinte : le plan de toute ligne de basse.",
        explainEn: "Root, third, fifth: the blueprint of every bass line.",
      },
      {
        qFr: "La gamme de Do majeur contient…",
        qEn: "The C major scale contains…",
        optionsFr: ["que des notes naturelles", "un Fa#", "un Si bémol", "un Sol#"],
        optionsEn: ["only natural notes", "an F#", "a Bb", "a G#"],
        answer: 0,
        explainFr: "Do majeur : aucune altération, que des touches blanches.",
        explainEn: "C major: no accidentals, white keys only.",
      },
      {
        qFr: "Mineure contre majeure : que change la tierce ?",
        qEn: "Minor vs major: what changes on the third?",
        optionsFr: ["+4 au lieu de +3", "+3 au lieu de +4", "+5 au lieu de +7", "Rien"],
        optionsEn: ["+4 instead of +3", "+3 instead of +4", "+5 instead of +7", "Nothing"],
        answer: 1,
        explainFr: "Une case plus bas, et la lumière devient mélancolie.",
        explainEn: "One fret lower, and light turns to melancholy.",
      },
    ],
  },
  {
    id: "basse-groove",
    titleFr: "Groover : patterns et espace",
    titleEn: "Grooving: patterns and space",
    introFr: [
      "Trois schémas portent presque tout : fondamentale–quinte (le pain quotidien), octaves rebondissantes (disco, funk), et walking I–VI–II–V (une fondamentale par accord, jazz).",
      "La règle d'or : servir la chanson. Joue avec la grosse caisse, laisse respirer entre les phrases — le silence groove aussi.",
    ],
    introEn: [
      "Three shapes carry almost everything: root–fifth (the daily bread), bouncing octaves (disco, funk), and I–VI–II–V walking (one root per chord, jazz).",
      "The golden rule: serve the song. Play with the kick, leave air between phrases — silence grooves too.",
    ],
    questions: [
      {
        qFr: "Le pattern du quotidien, c'est…",
        qEn: "The everyday pattern is…",
        optionsFr: ["fondamentale – quinte", "tierce – septième", "que des octaves", "chromatismes partout"],
        optionsEn: ["root – fifth", "third – seventh", "octaves only", "chromatics everywhere"],
        answer: 0,
        explainFr: "Tonique sur les temps, quinte pour respirer.",
        explainEn: "Root on the beats, fifth to breathe.",
      },
      {
        qFr: "Walking en Do : après Do (I), le VI c'est…",
        qEn: "Walking in C: after C (I), the VI is…",
        optionsFr: ["Sol (G)", "La (A)", "Fa (F)", "Ré (D)"],
        optionsEn: ["G", "A", "F", "D"],
        answer: 1,
        explainFr: "I–VI–II–V en Do : Do – La – Ré – Sol.",
        explainEn: "I–VI–II–V in C: C – A – D – G.",
      },
      {
        qFr: "Une octave, c'est…",
        qEn: "One octave is…",
        optionsFr: ["12 demi-tons", "7 demi-tons", "5 demi-tons", "10 demi-tons"],
        optionsEn: ["12 semitones", "7 semitones", "5 semitones", "10 semitones"],
        answer: 0,
        explainFr: "12 cases sur une corde, ou la forme 2+2.",
        explainEn: "12 frets on one string, or the 2+2 shape.",
      },
      {
        qFr: "La règle d'or du groove ?",
        qEn: "The golden rule of groove?",
        optionsFr: ["Jouer le plus de notes", "Servir la chanson, avec la grosse caisse", "Toujours slap", "Ne jamais répéter"],
        optionsEn: ["Play the most notes", "Serve the song, with the kick", "Always slap", "Never repeat"],
        answer: 1,
        explainFr: "Juste, en place, avec le batteur : c'est tout le métier.",
        explainEn: "In tune, in time, with the drummer: that's the whole craft.",
      },
    ],
  },
];

export const BASSE_EXAM: InstExam = {
  id: "basse-examen",
  titleFr: "Examen du bassiste",
  titleEn: "Bassist exam",
  leadFr: "6 questions sur tout le parcours basse. 60 % pour valider, +50 XP et badge Expert.",
  leadEn: "6 questions across the whole bass path. 60% to pass, +50 XP and the Expert badge.",
  questions: [
    {
      qFr: "Accordage standard de la basse, du grave à l'aigu ?",
      qEn: "Standard bass tuning, low to high?",
      optionsFr: ["Mi – La – Ré – Sol", "Mi – La – Ré – Sol – Si", "Ré – Sol – Si – Mi", "La – Ré – Sol – Do"],
      optionsEn: ["E – A – D – G", "E – A – D – G – B", "D – G – B – E", "A – D – G – C"],
      answer: 0,
      explainFr: "4 cordes : Mi, La, Ré, Sol.",
      explainEn: "4 strings: E, A, D, G.",
    },
    {
      qFr: "Corde de Ré, case 2 : quelle note ?",
      qEn: "D string, fret 2: which note?",
      optionsFr: ["Fa (F)", "Mi (E)", "Do (C)", "Sol (G)"],
      optionsEn: ["F", "E", "C", "G"],
      answer: 1,
      explainFr: "Ré + 2 demi-tons = Mi.",
      explainEn: "D + 2 semitones = E.",
    },
    {
      qFr: "Une triade majeure empile…",
      qEn: "A major triad stacks…",
      optionsFr: ["3 quintes", "fondamentale, tierce majeure, quinte", "fondamentale, seconde, sixte", "4 tierces"],
      optionsEn: ["3 fifths", "root, major third, fifth", "root, second, sixth", "4 thirds"],
      answer: 1,
      explainFr: "1 – 3 – 5 : le squelette de tes lignes.",
      explainEn: "1 – 3 – 5: the skeleton of your lines.",
    },
    {
      qFr: "La tierce mineure vaut…",
      qEn: "The minor third is…",
      optionsFr: ["4 demi-tons", "2 demi-tons", "3 demi-tons", "6 demi-tons"],
      optionsEn: ["4 semitones", "2 semitones", "3 semitones", "6 semitones"],
      answer: 2,
      explainFr: "Un demi-ton sous la majeure : la couleur mineure.",
      explainEn: "A semitone under the major: the minor color.",
    },
    {
      qFr: "Sur un blues en Mi, première fondamentale à jouer ?",
      qEn: "On an E blues, first root to play?",
      optionsFr: ["Mi (E)", "La (A)", "Si (B)", "Sol (G)"],
      optionsEn: ["E", "A", "B", "G"],
      answer: 0,
      explainFr: "Le blues en Mi commence sur Mi : fondamentale d'abord.",
      explainEn: "E blues starts on E: root first.",
    },
    {
      qFr: "Le binôme rythmique du bassiste ?",
      qEn: "The bassist's rhythmic partner?",
      optionsFr: ["La cymbale crash", "Le chanteur", "La grosse caisse", "Le clavier"],
      optionsEn: ["The crash cymbal", "The singer", "The kick drum", "The keys"],
      answer: 2,
      explainFr: "Basse + grosse caisse verrouillées : le moteur du groupe.",
      explainEn: "Locked bass + kick: the band's engine.",
    },
  ],
};
