/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CarnetRouteImport } from './routes/carnet'
import { Route as DefiRouteImport } from './routes/defi'
import { Route as DiagnosticRouteImport } from './routes/diagnostic'
import { Route as ExamensRouteImport } from './routes/examens'
import { Route as JeuxRouteImport } from './routes/jeux'
import { Route as MancheRouteImport } from './routes/manche'
import { Route as OreilleRouteImport } from './routes/oreille'
import { Route as ParcoursRouteImport } from './routes/parcours'
import { Route as ProgressionRouteImport } from './routes/progression'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as JeuxIdRouteImport } from './routes/jeux.$id'
import { Route as LeconIdRouteImport } from './routes/lecon.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CarnetRoute = CarnetRouteImport.update({
  id: '/carnet',
  path: '/carnet',
  getParentRoute: () => rootRouteImport,
} as any)
const DefiRoute = DefiRouteImport.update({
  id: '/defi',
  path: '/defi',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticRoute = DiagnosticRouteImport.update({
  id: '/diagnostic',
  path: '/diagnostic',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamensRoute = ExamensRouteImport.update({
  id: '/examens',
  path: '/examens',
  getParentRoute: () => rootRouteImport,
} as any)
const JeuxRoute = JeuxRouteImport.update({
  id: '/jeux',
  path: '/jeux',
  getParentRoute: () => rootRouteImport,
} as any)
const MancheRoute = MancheRouteImport.update({
  id: '/manche',
  path: '/manche',
  getParentRoute: () => rootRouteImport,
} as any)
const OreilleRoute = OreilleRouteImport.update({
  id: '/oreille',
  path: '/oreille',
  getParentRoute: () => rootRouteImport,
} as any)
const ParcoursRoute = ParcoursRouteImport.update({
  id: '/parcours',
  path: '/parcours',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressionRoute = ProgressionRouteImport.update({
  id: '/progression',
  path: '/progression',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const JeuxIdRoute = JeuxIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => JeuxRoute,
} as any)
const LeconIdRoute = LeconIdRouteImport.update({
  id: '/lecon/$id',
  path: '/lecon/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/carnet': typeof CarnetRoute
  '/defi': typeof DefiRoute
  '/diagnostic': typeof DiagnosticRoute
  '/examens': typeof ExamensRoute
  '/jeux': typeof JeuxRouteWithChildren
  '/manche': typeof MancheRoute
  '/oreille': typeof OreilleRoute
  '/parcours': typeof ParcoursRoute
  '/progression': typeof ProgressionRoute
  '/studio': typeof StudioRoute
  '/jeux/$id': typeof JeuxIdRoute
  '/lecon/$id': typeof LeconIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/carnet': typeof CarnetRoute
  '/defi': typeof DefiRoute
  '/diagnostic': typeof DiagnosticRoute
  '/examens': typeof ExamensRoute
  '/jeux': typeof JeuxRouteWithChildren
  '/manche': typeof MancheRoute
  '/oreille': typeof OreilleRoute
  '/parcours': typeof ParcoursRoute
  '/progression': typeof ProgressionRoute
  '/studio': typeof StudioRoute
  '/jeux/$id': typeof JeuxIdRoute
  '/lecon/$id': typeof LeconIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/carnet': typeof CarnetRoute
  '/defi': typeof DefiRoute
  '/diagnostic': typeof DiagnosticRoute
  '/examens': typeof ExamensRoute
  '/jeux': typeof JeuxRouteWithChildren
  '/manche': typeof MancheRoute
  '/oreille': typeof OreilleRoute
  '/parcours': typeof ParcoursRoute
  '/progression': typeof ProgressionRoute
  '/studio': typeof StudioRoute
  '/jeux/$id': typeof JeuxIdRoute
  '/lecon/$id': typeof LeconIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/carnet'
    | '/defi'
    | '/diagnostic'
    | '/examens'
    | '/jeux'
    | '/manche'
    | '/oreille'
    | '/parcours'
    | '/progression'
    | '/studio'
    | '/jeux/$id'
    | '/lecon/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/carnet'
    | '/defi'
    | '/diagnostic'
    | '/examens'
    | '/jeux'
    | '/manche'
    | '/oreille'
    | '/parcours'
    | '/progression'
    | '/studio'
    | '/jeux/$id'
    | '/lecon/$id'
  id:
    | '__root__'
    | '/'
    | '/carnet'
    | '/defi'
    | '/diagnostic'
    | '/examens'
    | '/jeux'
    | '/manche'
    | '/oreille'
    | '/parcours'
    | '/progression'
    | '/studio'
    | '/jeux/$id'
    | '/lecon/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CarnetRoute: typeof CarnetRoute
  DefiRoute: typeof DefiRoute
  DiagnosticRoute: typeof DiagnosticRoute
  ExamensRoute: typeof ExamensRoute
  JeuxRoute: typeof JeuxRouteWithChildren
  MancheRoute: typeof MancheRoute
  OreilleRoute: typeof OreilleRoute
  ParcoursRoute: typeof ParcoursRoute
  ProgressionRoute: typeof ProgressionRoute
  StudioRoute: typeof StudioRoute
  LeconIdRoute: typeof LeconIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carnet': {
      id: '/carnet'
      path: '/carnet'
      fullPath: '/carnet'
      preLoaderRoute: typeof CarnetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/defi': {
      id: '/defi'
      path: '/defi'
      fullPath: '/defi'
      preLoaderRoute: typeof DefiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostic': {
      id: '/diagnostic'
      path: '/diagnostic'
      fullPath: '/diagnostic'
      preLoaderRoute: typeof DiagnosticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examens': {
      id: '/examens'
      path: '/examens'
      fullPath: '/examens'
      preLoaderRoute: typeof ExamensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jeux': {
      id: '/jeux'
      path: '/jeux'
      fullPath: '/jeux'
      preLoaderRoute: typeof JeuxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manche': {
      id: '/manche'
      path: '/manche'
      fullPath: '/manche'
      preLoaderRoute: typeof MancheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oreille': {
      id: '/oreille'
      path: '/oreille'
      fullPath: '/oreille'
      preLoaderRoute: typeof OreilleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parcours': {
      id: '/parcours'
      path: '/parcours'
      fullPath: '/parcours'
      preLoaderRoute: typeof ParcoursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progression': {
      id: '/progression'
      path: '/progression'
      fullPath: '/progression'
      preLoaderRoute: typeof ProgressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jeux/$id': {
      id: '/jeux/$id'
      path: '/$id'
      fullPath: '/jeux/$id'
      preLoaderRoute: typeof JeuxIdRouteImport
      parentRoute: typeof JeuxRoute
    }
    '/lecon/$id': {
      id: '/lecon/$id'
      path: '/lecon/$id'
      fullPath: '/lecon/$id'
      preLoaderRoute: typeof LeconIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface JeuxRouteChildren {
  JeuxIdRoute: typeof JeuxIdRoute
}

const JeuxRouteChildren: JeuxRouteChildren = {
  JeuxIdRoute: JeuxIdRoute,
}

const JeuxRouteWithChildren = JeuxRoute._addFileChildren(JeuxRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CarnetRoute: CarnetRoute,
  DefiRoute: DefiRoute,
  DiagnosticRoute: DiagnosticRoute,
  ExamensRoute: ExamensRoute,
  JeuxRoute: JeuxRouteWithChildren,
  MancheRoute: MancheRoute,
  OreilleRoute: OreilleRoute,
  ParcoursRoute: ParcoursRoute,
  ProgressionRoute: ProgressionRoute,
  StudioRoute: StudioRoute,
  LeconIdRoute: LeconIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
